// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client.proto

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type C_A_LoginRequest struct {
	PacketHead       *Ipacket `protobuf:"bytes,1,req,name=PacketHead" json:"PacketHead,omitempty"`
	AccountName      *string  `protobuf:"bytes,2,req,name=AccountName" json:"AccountName,omitempty"`
	BuildNo          *string  `protobuf:"bytes,3,req,name=BuildNo" json:"BuildNo,omitempty"`
	SocketId         *int32   `protobuf:"varint,4,req,name=SocketId" json:"SocketId,omitempty"`
	Password         *string  `protobuf:"bytes,5,req,name=Password" json:"Password,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *C_A_LoginRequest) Reset()                    { *m = C_A_LoginRequest{} }
func (m *C_A_LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*C_A_LoginRequest) ProtoMessage()               {}
func (*C_A_LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *C_A_LoginRequest) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *C_A_LoginRequest) GetAccountName() string {
	if m != nil && m.AccountName != nil {
		return *m.AccountName
	}
	return ""
}

func (m *C_A_LoginRequest) GetBuildNo() string {
	if m != nil && m.BuildNo != nil {
		return *m.BuildNo
	}
	return ""
}

func (m *C_A_LoginRequest) GetSocketId() int32 {
	if m != nil && m.SocketId != nil {
		return *m.SocketId
	}
	return 0
}

func (m *C_A_LoginRequest) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

type C_A_LoginRequest1 struct {
	Login            *C_A_LoginRequest `protobuf:"bytes,1,req,name=Login" json:"Login,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *C_A_LoginRequest1) Reset()                    { *m = C_A_LoginRequest1{} }
func (m *C_A_LoginRequest1) String() string            { return proto.CompactTextString(m) }
func (*C_A_LoginRequest1) ProtoMessage()               {}
func (*C_A_LoginRequest1) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *C_A_LoginRequest1) GetLogin() *C_A_LoginRequest {
	if m != nil {
		return m.Login
	}
	return nil
}

type C_A_RegisterRequest struct {
	PacketHead       *Ipacket `protobuf:"bytes,1,req,name=PacketHead" json:"PacketHead,omitempty"`
	AccountName      *string  `protobuf:"bytes,2,req,name=AccountName" json:"AccountName,omitempty"`
	SocketId         *int32   `protobuf:"varint,3,req,name=SocketId" json:"SocketId,omitempty"`
	Password         *string  `protobuf:"bytes,4,req,name=Password" json:"Password,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *C_A_RegisterRequest) Reset()                    { *m = C_A_RegisterRequest{} }
func (m *C_A_RegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*C_A_RegisterRequest) ProtoMessage()               {}
func (*C_A_RegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *C_A_RegisterRequest) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *C_A_RegisterRequest) GetAccountName() string {
	if m != nil && m.AccountName != nil {
		return *m.AccountName
	}
	return ""
}

func (m *C_A_RegisterRequest) GetSocketId() int32 {
	if m != nil && m.SocketId != nil {
		return *m.SocketId
	}
	return 0
}

func (m *C_A_RegisterRequest) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

type C_W_CreatePlayerRequest struct {
	PacketHead       *Ipacket `protobuf:"bytes,1,req,name=PacketHead" json:"PacketHead,omitempty"`
	PlayerName       *string  `protobuf:"bytes,2,req,name=PlayerName" json:"PlayerName,omitempty"`
	Sex              *int32   `protobuf:"varint,3,req,name=Sex" json:"Sex,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *C_W_CreatePlayerRequest) Reset()                    { *m = C_W_CreatePlayerRequest{} }
func (m *C_W_CreatePlayerRequest) String() string            { return proto.CompactTextString(m) }
func (*C_W_CreatePlayerRequest) ProtoMessage()               {}
func (*C_W_CreatePlayerRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *C_W_CreatePlayerRequest) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *C_W_CreatePlayerRequest) GetPlayerName() string {
	if m != nil && m.PlayerName != nil {
		return *m.PlayerName
	}
	return ""
}

func (m *C_W_CreatePlayerRequest) GetSex() int32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

type C_W_Game_LoginRequset struct {
	PacketHead       *Ipacket `protobuf:"bytes,1,req,name=PacketHead" json:"PacketHead,omitempty"`
	PlayerId         *int64   `protobuf:"varint,2,req,name=PlayerId" json:"PlayerId,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *C_W_Game_LoginRequset) Reset()                    { *m = C_W_Game_LoginRequset{} }
func (m *C_W_Game_LoginRequset) String() string            { return proto.CompactTextString(m) }
func (*C_W_Game_LoginRequset) ProtoMessage()               {}
func (*C_W_Game_LoginRequset) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *C_W_Game_LoginRequset) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *C_W_Game_LoginRequset) GetPlayerId() int64 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

type C_G_LogoutResponse struct {
	PacketHead       *Ipacket `protobuf:"bytes,1,req,name=PacketHead" json:"PacketHead,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *C_G_LogoutResponse) Reset()                    { *m = C_G_LogoutResponse{} }
func (m *C_G_LogoutResponse) String() string            { return proto.CompactTextString(m) }
func (*C_G_LogoutResponse) ProtoMessage()               {}
func (*C_G_LogoutResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *C_G_LogoutResponse) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

type C_W_ChatMessage struct {
	PacketHead       *Ipacket `protobuf:"bytes,1,req,name=PacketHead" json:"PacketHead,omitempty"`
	Sender           *int64   `protobuf:"varint,2,req,name=Sender" json:"Sender,omitempty"`
	Recver           *int64   `protobuf:"varint,3,req,name=Recver" json:"Recver,omitempty"`
	MessageType      *int32   `protobuf:"varint,4,req,name=MessageType" json:"MessageType,omitempty"`
	Message          *string  `protobuf:"bytes,5,req,name=Message" json:"Message,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *C_W_ChatMessage) Reset()                    { *m = C_W_ChatMessage{} }
func (m *C_W_ChatMessage) String() string            { return proto.CompactTextString(m) }
func (*C_W_ChatMessage) ProtoMessage()               {}
func (*C_W_ChatMessage) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *C_W_ChatMessage) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *C_W_ChatMessage) GetSender() int64 {
	if m != nil && m.Sender != nil {
		return *m.Sender
	}
	return 0
}

func (m *C_W_ChatMessage) GetRecver() int64 {
	if m != nil && m.Recver != nil {
		return *m.Recver
	}
	return 0
}

func (m *C_W_ChatMessage) GetMessageType() int32 {
	if m != nil && m.MessageType != nil {
		return *m.MessageType
	}
	return 0
}

func (m *C_W_ChatMessage) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

type W_C_ChatMessage struct {
	PacketHead       *Ipacket `protobuf:"bytes,1,req,name=PacketHead" json:"PacketHead,omitempty"`
	Sender           *int64   `protobuf:"varint,2,req,name=Sender" json:"Sender,omitempty"`
	SenderName       *string  `protobuf:"bytes,3,req,name=SenderName" json:"SenderName,omitempty"`
	Recver           *int64   `protobuf:"varint,4,req,name=Recver" json:"Recver,omitempty"`
	RecverName       *string  `protobuf:"bytes,5,req,name=RecverName" json:"RecverName,omitempty"`
	MessageType      *int32   `protobuf:"varint,6,req,name=MessageType" json:"MessageType,omitempty"`
	Message          *string  `protobuf:"bytes,7,req,name=Message" json:"Message,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *W_C_ChatMessage) Reset()                    { *m = W_C_ChatMessage{} }
func (m *W_C_ChatMessage) String() string            { return proto.CompactTextString(m) }
func (*W_C_ChatMessage) ProtoMessage()               {}
func (*W_C_ChatMessage) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *W_C_ChatMessage) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *W_C_ChatMessage) GetSender() int64 {
	if m != nil && m.Sender != nil {
		return *m.Sender
	}
	return 0
}

func (m *W_C_ChatMessage) GetSenderName() string {
	if m != nil && m.SenderName != nil {
		return *m.SenderName
	}
	return ""
}

func (m *W_C_ChatMessage) GetRecver() int64 {
	if m != nil && m.Recver != nil {
		return *m.Recver
	}
	return 0
}

func (m *W_C_ChatMessage) GetRecverName() string {
	if m != nil && m.RecverName != nil {
		return *m.RecverName
	}
	return ""
}

func (m *W_C_ChatMessage) GetMessageType() int32 {
	if m != nil && m.MessageType != nil {
		return *m.MessageType
	}
	return 0
}

func (m *W_C_ChatMessage) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*C_A_LoginRequest)(nil), "message.C_A_LoginRequest")
	proto.RegisterType((*C_A_LoginRequest1)(nil), "message.C_A_LoginRequest1")
	proto.RegisterType((*C_A_RegisterRequest)(nil), "message.C_A_RegisterRequest")
	proto.RegisterType((*C_W_CreatePlayerRequest)(nil), "message.C_W_CreatePlayerRequest")
	proto.RegisterType((*C_W_Game_LoginRequset)(nil), "message.C_W_Game_LoginRequset")
	proto.RegisterType((*C_G_LogoutResponse)(nil), "message.C_G_LogoutResponse")
	proto.RegisterType((*C_W_ChatMessage)(nil), "message.C_W_ChatMessage")
	proto.RegisterType((*W_C_ChatMessage)(nil), "message.W_C_ChatMessage")
}

func init() { proto.RegisterFile("client.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 416 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0xcd, 0xce, 0xd2, 0x40,
	0x14, 0x4d, 0x5b, 0xf8, 0xd0, 0xfb, 0x69, 0x3e, 0x1c, 0xa3, 0xd6, 0x6f, 0x41, 0x9a, 0xae, 0x58,
	0xe1, 0xcf, 0x1b, 0x60, 0x8d, 0x48, 0xa2, 0x84, 0x0c, 0x26, 0x2c, 0x9b, 0x49, 0x7b, 0x83, 0x8d,
	0xd0, 0xa9, 0x9d, 0xa9, 0xca, 0xc2, 0x87, 0xf1, 0x09, 0xdc, 0xfa, 0x56, 0xbe, 0x82, 0x99, 0x1f,
	0xea, 0xd0, 0x05, 0x89, 0x18, 0x76, 0xf7, 0x9c, 0x7b, 0xa7, 0xe7, 0x9c, 0xdb, 0x19, 0xb8, 0x97,
	0x6d, 0x0b, 0x2c, 0xe5, 0xa4, 0xaa, 0xb9, 0xe4, 0x64, 0xb0, 0x43, 0x21, 0xd8, 0x06, 0x6f, 0xef,
	0xdb, 0xc2, 0xf0, 0xf1, 0x2f, 0x0f, 0x86, 0x49, 0x3a, 0x4d, 0xdf, 0xf1, 0x4d, 0x51, 0x52, 0xfc,
	0xdc, 0xa0, 0x90, 0xe4, 0x39, 0xc0, 0x92, 0x65, 0x9f, 0x50, 0xbe, 0x45, 0x96, 0x87, 0x5e, 0xe4,
	0x8f, 0xaf, 0x5f, 0x0e, 0x27, 0x87, 0x83, 0xf3, 0x4a, 0xf7, 0xa8, 0x33, 0x43, 0x22, 0xb8, 0x9e,
	0x66, 0x19, 0x6f, 0x4a, 0xb9, 0x60, 0x3b, 0x0c, 0xfd, 0xc8, 0x1f, 0xdf, 0xa5, 0x2e, 0x45, 0x42,
	0x18, 0xbc, 0x6a, 0x8a, 0x6d, 0xbe, 0xe0, 0x61, 0xa0, 0xbb, 0x07, 0x48, 0x6e, 0xe1, 0xce, 0x8a,
	0xab, 0x2f, 0xcd, 0xf3, 0xb0, 0x17, 0xf9, 0xe3, 0x3e, 0x6d, 0xb1, 0xea, 0x2d, 0x99, 0x10, 0x5f,
	0x79, 0x9d, 0x87, 0x7d, 0x7d, 0xac, 0xc5, 0xf1, 0x6b, 0x78, 0xd0, 0x75, 0xfe, 0x82, 0x3c, 0x83,
	0xbe, 0x26, 0xac, 0xeb, 0xa7, 0xad, 0xeb, 0xee, 0x28, 0x35, 0x73, 0xf1, 0x0f, 0x0f, 0x1e, 0xaa,
	0x1e, 0xc5, 0x4d, 0x21, 0x24, 0xd6, 0x97, 0xdc, 0x81, 0x9b, 0x34, 0x38, 0x91, 0xb4, 0xd7, 0x49,
	0xfa, 0x1d, 0x9e, 0x24, 0xe9, 0x3a, 0x4d, 0x6a, 0x64, 0x12, 0x97, 0x5b, 0xb6, 0xff, 0x1f, 0x9b,
	0x23, 0x00, 0xf3, 0x09, 0xc7, 0xa5, 0xc3, 0x90, 0x21, 0x04, 0x2b, 0xfc, 0x66, 0xfd, 0xa9, 0x32,
	0x46, 0x78, 0xa4, 0xe4, 0x67, 0x6c, 0x87, 0x7f, 0x57, 0x28, 0xf0, 0x1c, 0x71, 0x95, 0x52, 0x4b,
	0xcd, 0x73, 0x2d, 0x1d, 0xd0, 0x16, 0xc7, 0x6f, 0x80, 0x24, 0xe9, 0x4c, 0x29, 0xf0, 0x46, 0x52,
	0x14, 0x15, 0x2f, 0x05, 0xfe, 0xbb, 0x46, 0xfc, 0xd3, 0x83, 0x1b, 0xbd, 0xae, 0x8f, 0x4c, 0xbe,
	0x37, 0x73, 0x67, 0x38, 0x7d, 0x0c, 0x57, 0x2b, 0x2c, 0x73, 0xac, 0xad, 0x4f, 0x8b, 0x14, 0x4f,
	0x31, 0xfb, 0x82, 0xb5, 0xde, 0x50, 0x40, 0x2d, 0x52, 0x7f, 0xdf, 0x8a, 0x7d, 0xd8, 0x57, 0x68,
	0x2f, 0xb2, 0x4b, 0xa9, 0x17, 0x60, 0xa1, 0xbd, 0xca, 0x07, 0x18, 0xff, 0xf6, 0xe0, 0x66, 0x9d,
	0x26, 0x17, 0x72, 0x3c, 0x02, 0x30, 0x95, 0xfe, 0xe1, 0xe6, 0xf1, 0x39, 0x8c, 0x93, 0xa8, 0x77,
	0x94, 0x68, 0x04, 0x60, 0x2a, 0x7d, 0xce, 0x58, 0x76, 0x98, 0x6e, 0xe2, 0xab, 0x93, 0x89, 0x07,
	0x47, 0x89, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xc3, 0xa4, 0xab, 0x26, 0x9d, 0x04, 0x00, 0x00,
}
